image: ruby:2.5.1
clone:
  depth: full
pipelines:
  branches:
    staging:
      - step:
          script:
            - git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING_APP_NAME.git HEAD:master