-- CREATE TABLE posts(
--   id SERIAL PRIMARY KEY,
--   post VARCHAR ( 255 ),
--   mail VARCHAR ( 100 ),
--   accepted BOOLEAN,
--   created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );

CREATE TABLE statements(
id SERIAL PRIMARY KEY,
BW_id VARCHAR,
user_statement VARCHAR ( 280 ),
accepted BOOLEAN,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

